# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(798, 594)
        MainWindow.setStyleSheet(".QLabel {\n"
"    font-size: 20px;\n"
"}\n"
"\n"
".QPushButton {\n"
"    font-size: 20px;\n"
"    border: none;\n"
"    background-color: #9C9C9C;\n"
"}\n"
"\n"
"#label_3 {\n"
"    font-size: 21px;\n"
"}\n"
"\n"
".QPushButton:hover {\n"
"    background-color: black;\n"
"    color: white;\n"
"}\n"
"\n"
".QTabWidget {\n"
"    font-size: 14px;\n"
"}  \n"
"\n"
"#humidity, #humidity_value, #rain_prob, #rain_prob_value, #status, #status_value, #temps, #temps_value, #wind_speed, #wind_speed_value, #sick, #recovered, #sick_change_value, #dead, #sick_change, #dollar, #eur, #yuan, #oil {\n"
"    color: white;\n"
"}\n"
"\n"
"#dead_value {\n"
"    color: red;\n"
"}\n"
"\n"
"#recovered_value {\n"
"    color: green;\n"
"}\n"
"\n"
"#sick_value {\n"
"    color: yellow;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 801, 541))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.weather_icon = QtWidgets.QLabel(self.tab)
        self.weather_icon.setGeometry(QtCore.QRect(30, 20, 51, 51))
        self.weather_icon.setText("")
        self.weather_icon.setTextFormat(QtCore.Qt.AutoText)
        self.weather_icon.setPixmap(QtGui.QPixmap("weather_icon.png"))
        self.weather_icon.setObjectName("weather_icon")
        self.weather = QtWidgets.QLabel(self.tab)
        self.weather.setGeometry(QtCore.QRect(80, 30, 71, 31))
        self.weather.setObjectName("weather")
        self.weather_today = QtWidgets.QPushButton(self.tab)
        self.weather_today.setGeometry(QtCore.QRect(280, 20, 131, 41))
        self.weather_today.setObjectName("weather_today")
        self.weather_tomorrow = QtWidgets.QPushButton(self.tab)
        self.weather_tomorrow.setGeometry(QtCore.QRect(440, 20, 121, 41))
        self.weather_tomorrow.setObjectName("weather_tomorrow")
        self.weather_after_tomorrow = QtWidgets.QPushButton(self.tab)
        self.weather_after_tomorrow.setGeometry(QtCore.QRect(600, 20, 161, 41))
        self.weather_after_tomorrow.setObjectName("weather_after_tomorrow")
        self.background_img = QtWidgets.QLabel(self.tab)
        self.background_img.setEnabled(True)
        self.background_img.setGeometry(QtCore.QRect(0, 80, 821, 431))
        self.background_img.setStyleSheet("")
        self.background_img.setText("")
        self.background_img.setPixmap(QtGui.QPixmap("clouds-small.jpg"))
        self.background_img.setObjectName("background_img")
        self.bg_img = QtWidgets.QLabel(self.tab)
        self.bg_img.setGeometry(QtCore.QRect(-10, 80, 811, 441))
        self.bg_img.setText("")
        self.bg_img.setPixmap(QtGui.QPixmap("clouds-small.png"))
        self.bg_img.setObjectName("bg_img")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(100, 100, 631, 361))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.wind_speed = QtWidgets.QLabel(self.gridLayoutWidget)
        self.wind_speed.setObjectName("wind_speed")
        self.gridLayout.addWidget(self.wind_speed, 2, 0, 1, 1)
        self.rain_prob = QtWidgets.QLabel(self.gridLayoutWidget)
        self.rain_prob.setObjectName("rain_prob")
        self.gridLayout.addWidget(self.rain_prob, 3, 0, 1, 1)
        self.humidity = QtWidgets.QLabel(self.gridLayoutWidget)
        self.humidity.setObjectName("humidity")
        self.gridLayout.addWidget(self.humidity, 1, 0, 1, 1)
        self.wind_speed_value = QtWidgets.QLabel(self.gridLayoutWidget)
        self.wind_speed_value.setText("")
        self.wind_speed_value.setObjectName("wind_speed_value")
        self.gridLayout.addWidget(self.wind_speed_value, 2, 1, 1, 1)
        self.humidity_value = QtWidgets.QLabel(self.gridLayoutWidget)
        self.humidity_value.setText("")
        self.humidity_value.setObjectName("humidity_value")
        self.gridLayout.addWidget(self.humidity_value, 1, 1, 1, 1)
        self.rain_prob_value = QtWidgets.QLabel(self.gridLayoutWidget)
        self.rain_prob_value.setText("")
        self.rain_prob_value.setObjectName("rain_prob_value")
        self.gridLayout.addWidget(self.rain_prob_value, 3, 1, 1, 1)
        self.temps_value = QtWidgets.QLabel(self.gridLayoutWidget)
        self.temps_value.setText("")
        self.temps_value.setObjectName("temps_value")
        self.gridLayout.addWidget(self.temps_value, 0, 1, 1, 1)
        self.temps = QtWidgets.QLabel(self.gridLayoutWidget)
        self.temps.setObjectName("temps")
        self.gridLayout.addWidget(self.temps, 0, 0, 1, 1)
        self.status = QtWidgets.QLabel(self.gridLayoutWidget)
        self.status.setText("")
        self.status.setObjectName("status")
        self.gridLayout.addWidget(self.status, 4, 0, 1, 1)
        self.status_value = QtWidgets.QLabel(self.gridLayoutWidget)
        self.status_value.setText("")
        self.status_value.setObjectName("status_value")
        self.gridLayout.addWidget(self.status_value, 4, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.corona_icon = QtWidgets.QLabel(self.tab_2)
        self.corona_icon.setGeometry(QtCore.QRect(30, 30, 51, 51))
        self.corona_icon.setText("")
        self.corona_icon.setPixmap(QtGui.QPixmap("covid_icon.png"))
        self.corona_icon.setObjectName("corona_icon")
        self.corona_name = QtWidgets.QLabel(self.tab_2)
        self.corona_name.setGeometry(QtCore.QRect(80, 50, 131, 31))
        self.corona_name.setObjectName("corona_name")
        self.in_rus = QtWidgets.QPushButton(self.tab_2)
        self.in_rus.setGeometry(QtCore.QRect(250, 40, 121, 41))
        self.in_rus.setObjectName("in_rus")
        self.in_amur = QtWidgets.QPushButton(self.tab_2)
        self.in_amur.setGeometry(QtCore.QRect(410, 40, 201, 41))
        self.in_amur.setObjectName("in_amur")
        self.in_world = QtWidgets.QPushButton(self.tab_2)
        self.in_world.setGeometry(QtCore.QRect(650, 40, 131, 41))
        self.in_world.setObjectName("in_world")
        self.bg_img_2 = QtWidgets.QLabel(self.tab_2)
        self.bg_img_2.setGeometry(QtCore.QRect(-10, 100, 811, 431))
        self.bg_img_2.setText("")
        self.bg_img_2.setPixmap(QtGui.QPixmap("clouds-small.png"))
        self.bg_img_2.setObjectName("bg_img_2")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(80, 120, 631, 361))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.recovered = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.recovered.setObjectName("recovered")
        self.gridLayout_2.addWidget(self.recovered, 1, 0, 1, 1)
        self.recovered_value = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.recovered_value.setText("")
        self.recovered_value.setObjectName("recovered_value")
        self.gridLayout_2.addWidget(self.recovered_value, 1, 1, 1, 1)
        self.sick = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.sick.setObjectName("sick")
        self.gridLayout_2.addWidget(self.sick, 0, 0, 1, 1)
        self.sick_value = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.sick_value.setText("")
        self.sick_value.setObjectName("sick_value")
        self.gridLayout_2.addWidget(self.sick_value, 0, 1, 1, 1)
        self.dead = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.dead.setObjectName("dead")
        self.gridLayout_2.addWidget(self.dead, 2, 0, 1, 1)
        self.dead_value = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.dead_value.setText("")
        self.dead_value.setObjectName("dead_value")
        self.gridLayout_2.addWidget(self.dead_value, 2, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.money_name = QtWidgets.QLabel(self.tab_3)
        self.money_name.setGeometry(QtCore.QRect(80, 50, 71, 20))
        self.money_name.setObjectName("money_name")
        self.course_money = QtWidgets.QPushButton(self.tab_3)
        self.course_money.setGeometry(QtCore.QRect(420, 30, 201, 51))
        self.course_money.setObjectName("course_money")
        self.money_icon = QtWidgets.QLabel(self.tab_3)
        self.money_icon.setGeometry(QtCore.QRect(30, 20, 51, 51))
        self.money_icon.setText("")
        self.money_icon.setPixmap(QtGui.QPixmap("money_icon.png"))
        self.money_icon.setObjectName("money_icon")
        self.bg_img_3 = QtWidgets.QLabel(self.tab_3)
        self.bg_img_3.setGeometry(QtCore.QRect(-10, 100, 811, 441))
        self.bg_img_3.setText("")
        self.bg_img_3.setPixmap(QtGui.QPixmap("clouds-small.png"))
        self.bg_img_3.setObjectName("bg_img_3")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.tab_3)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(90, 130, 591, 331))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.oil_value_change = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.oil_value_change.setText("")
        self.oil_value_change.setObjectName("oil_value_change")
        self.gridLayout_3.addWidget(self.oil_value_change, 3, 2, 1, 1)
        self.eur_value_change = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.eur_value_change.setText("")
        self.eur_value_change.setObjectName("eur_value_change")
        self.gridLayout_3.addWidget(self.eur_value_change, 1, 2, 1, 1)
        self.dollar_value = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.dollar_value.setText("")
        self.dollar_value.setObjectName("dollar_value")
        self.gridLayout_3.addWidget(self.dollar_value, 0, 1, 1, 1)
        self.oil_value = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.oil_value.setText("")
        self.oil_value.setObjectName("oil_value")
        self.gridLayout_3.addWidget(self.oil_value, 3, 1, 1, 1)
        self.dollar_value_change = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.dollar_value_change.setText("")
        self.dollar_value_change.setObjectName("dollar_value_change")
        self.gridLayout_3.addWidget(self.dollar_value_change, 0, 2, 1, 1)
        self.eur_value = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.eur_value.setText("")
        self.eur_value.setObjectName("eur_value")
        self.gridLayout_3.addWidget(self.eur_value, 1, 1, 1, 1)
        self.dollar = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.dollar.setObjectName("dollar")
        self.gridLayout_3.addWidget(self.dollar, 0, 0, 1, 1)
        self.eur = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.eur.setObjectName("eur")
        self.gridLayout_3.addWidget(self.eur, 1, 0, 1, 1)
        self.oil = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.oil.setObjectName("oil")
        self.gridLayout_3.addWidget(self.oil, 3, 0, 1, 1)
        self.yuan = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.yuan.setObjectName("yuan")
        self.gridLayout_3.addWidget(self.yuan, 2, 0, 1, 1)
        self.yuan_value = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.yuan_value.setText("")
        self.yuan_value.setObjectName("yuan_value")
        self.gridLayout_3.addWidget(self.yuan_value, 2, 1, 1, 1)
        self.yuan_value_change = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.yuan_value_change.setText("")
        self.yuan_value_change.setObjectName("yuan_value_change")
        self.gridLayout_3.addWidget(self.yuan_value_change, 2, 2, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(10, 550, 81, 31))
        self.exit.setObjectName("exit")
        self.time = QtWidgets.QLabel(self.centralwidget)
        self.time.setGeometry(QtCore.QRect(740, 550, 51, 31))
        self.time.setObjectName("time")
        self.now_temp = QtWidgets.QLabel(self.centralwidget)
        self.now_temp.setGeometry(QtCore.QRect(370, 550, 71, 31))
        self.now_temp.setObjectName("now_temp")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.exit.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.weather.setText(_translate("MainWindow", "погода"))
        self.weather_today.setText(_translate("MainWindow", "На сегодня"))
        self.weather_tomorrow.setText(_translate("MainWindow", "На завтра"))
        self.weather_after_tomorrow.setText(_translate("MainWindow", "На послезавтра"))
        self.wind_speed.setText(_translate("MainWindow", "Скорость ветра"))
        self.rain_prob.setText(_translate("MainWindow", "Вероятность осадков"))
        self.humidity.setText(_translate("MainWindow", "Влажность"))
        self.temps.setText(_translate("MainWindow", "Температуры"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Погода"))
        self.corona_name.setText(_translate("MainWindow", "коронавирус"))
        self.in_rus.setText(_translate("MainWindow", "В России"))
        self.in_amur.setText(_translate("MainWindow", "В Амурской области"))
        self.in_world.setText(_translate("MainWindow", "В мире"))
        self.recovered.setText(_translate("MainWindow", "Вылечившихся"))
        self.sick.setText(_translate("MainWindow", "Заболевших"))
        self.dead.setText(_translate("MainWindow", "Умерших"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "COVID-19"))
        self.money_name.setText(_translate("MainWindow", "валюта"))
        self.course_money.setText(_translate("MainWindow", "Узнать курс"))
        self.dollar.setText(_translate("MainWindow", "1 доллар"))
        self.eur.setText(_translate("MainWindow", "1 евро"))
        self.oil.setText(_translate("MainWindow", "1 баррель нефти "))
        self.yuan.setText(_translate("MainWindow", "1 юань"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Валюта"))
        self.exit.setText(_translate("MainWindow", "Выйти"))
        self.time.setText(_translate("MainWindow", "14:28"))
        self.now_temp.setText(_translate("MainWindow", "+14°С"))
